services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: stopodds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ../api
      dockerfile: ../infra/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/stopodds
      DEBUG: "true"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    volumes:
      - ../app:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: